services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: rebuild
          path: ./frontend
    networks:
      - backend-net

  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    develop:
      watch:
        - action: rebuild
          path: ./API
    networks:
      - backend-net
    volumes:
      - images_vol:/app/images

  mysql:
    image: 'mysql:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sql_db
      MYSQL_USER: victor
      MYSQL_PASSWORD: victor
    ports:
      - "3305:3306"
    networks:
      - backend-net
    volumes:
      - sql_db_vol:/var/lib/mysql

networks:
  backend-net:
    driver: bridge
  frontend-net:
    driver: bridge
  database-net:
    driver: bridge

volumes:
  sql_db_vol:
  images_vol:
